### ISSUE TITLE
Περιγραφικά ονόματα αρχείων και περιποίηση κώδικα

### ISSUE THREAD

**Issue by iloudaros** [iloudaros/CoVID69#9]
Πρέπει να επιστρέψουμε σε προηγούμενα αρχεία και να μετονομάσουμε όσα δεν περιγράφουν την λειτουργία τους. Επίσης
πρέπει να φροντίζουμε τα inclusions που κάνουμε σε html αρχεία να είναι οργανωμένα για να ξέρουμε τι είναι το καθένα.

Examples: "my.js", τα περιεχόμενα του "user_home.html" κοκ

**Comment by PSergiannis** [comment]
ok
